kind: Service
apiVersion: v1
metadata:
  name: petclinic-service
  namespace: petclinic-{{ .Values.environment }}
spec:
  selector:
    app: petclinic
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
