apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinc
      env: {{ .Values.environment }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: petclinic
        env: {{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Values.environment }}-petclinic
          image: 060299086407.dkr.ecr.us-east-1.amazonaws.com/petclinic:{{ .Values.imagetag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9966
